POST http://localhost:3000/api/offers
content-type:application/json

{
  "title": "Title",
  "mobile": "111222333",
  "category": "sale",
  "description": "Description",
  "location": "Location",
  "price": "123"
}

###
POST http://localhost:3000/api/users
content-type: application/json

{
  "email": "john@doe.com",
  "password": "123123123",
  "fullName": "John Doe"
}

###
GET http://localhost:3000/api/offers/paginate

###
GET http://localhost:3000/api/offers/paginate?category=sale

###
GET http://localhost:3000/api/offers/paginate?category=rent
